Blog_project/Blog/urls.py
from django.urls import path

from .views import index ,create_article , article_delete,article_update


urlpatterns = [
    path('', index, name='index'),
    path('create/',  create_article, name='create'), #article_delete
    path('delete/<int:id>',  article_delete, name='delete'),
    path('update/<int:id>',  article_update ,  name='update'),


    # we dont reference static url by hard code but we will reference url methods as
    # index  , create and so on.
    # another reaaon is that app dont know under what prefix he will be

]

Blog_project/Blog_project/urls.py
from django.contrib import admin
# from django.urls import path
from django.urls import include, path

# adding Django.conf.urls functions for use in URLconfs¶ --
# Helper function to return a URL pattern for serving files in debug mode:
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('Blog.urls')),
    path('', include('users.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog_project/users/urls.py
from django.urls import path

from .views import register ,login

app_name = 'users'
urlpatterns = [
    path('register', register, name='register'),
    path('login', login, name='login'),

]

Blog_project/Blog/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=100 , null=False , blank=False , unique=True)

    body = models.TextField(max_length=1000 , null=False , blank=False)

    posted_at = models.DateTimeField(auto_now_add=True)

    cover_photo = models.ImageField(upload_to='blog/articles/covers' , default='blog/articles/covers/default-cover.jpg')

    last_updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return ' {} Article '.format(self.title)

class KeyWord(models.Model):
    name = models.CharField(max_length=50 , null=False , blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article , on_delete=models.CASCADE , related_name='keywords') 

Blog_project/users/models.py
from django.db import models

# Create your models here.

Blog_project/Blog/forms.py
from django import forms
from .models import Article 


class ArticleForm(forms.ModelForm):
    #---- method1 to create form --
    # title = forms.CharField()
    # body = forms.CharField(widget=forms.Textarea)
    # cover_photo = forms.ImageField()
    #---- method2 to create form  ArticleForm  inherits --  forms.ModelForm not forms.Form
    class Meta:
        model = Article
        fields = [
            "cover_photo",
            'title',
            'body',
            
        ]

    # notes created_at and updated_at generated by default by timestamp..ok
    #  after we create the form we import it in view.py to pass it to form.html to render it

Blog_project/Blog/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse
from .models import Article
from .forms import ArticleForm #import it to use here 
from django.http import HttpResponseRedirect


# Create your views here.
# ******************* Index function *******
def index(request):
    allArticles =  Article.objects.order_by('-posted_at').all()
    return  render(request , 'index.html' , context={
        'articles' :allArticles
    })


# ******************* Create Article function *******
def create_article(request):
    if request.method == "POST":
         form = ArticleForm(request.POST)
         if form.is_valid():
             form.save()
             return redirect('index')
         return render (request  , 'form.html' , context={
            "form" : form
            })
    form = ArticleForm()
    return render (request  , 'form.html' , context={
        "form" : form
    })


# ******************* Delete Article function *******
def article_delete(request , id):
    # To delete it from an instance:
    instance = Article.objects.get(id=id)
    instance.delete()
    return redirect('index')

   
# ******************* Update Article function *******
def article_update(request , id):
    article = Article.objects.get(id=id)
    if request.method == "POST":
         form = ArticleForm(request.POST , instance=article)
         if form.is_valid():
             form.save()
             return redirect('index')
         return render (request  , 'edit.html' , context={
            "ArticleForm" : form,
            "ArticleModel":Article.objects.get(id=id)
            })
    else:
        form = ArticleForm()
        return render (request  , 'edit.html' , context={
           "ArticleForm" : form,
            "ArticleModel":Article.objects.get(id=id)
        })

Blog_project/users/views.py
from django.shortcuts import render , redirect
from django.contrib.auth .forms import UserCreationForm

# Create your views here.

# ******************* register function *******
def register(request):
    form = UserCreationForm()
    context={
        'RegisterForm':form
    }
    return render(request , 'users/register.html' , context)

# ******************* login function *******
def login(request):
    form = UserCreationForm()
    context={
        'RegisterForm':form
    }
    return render(request , 'users/register.html' , context)

Blog_project/Blog/templates/base.html
{%  extends 'nav.html' %}

{% block content %}






{% endblock  %}

Blog_project/Blog/templates/edit.html
{% extends 'base.html' %}

{% block content %}
<!-- we can build form by own or we can user Django form  -->
<!-- that provides us with power of validation on input field and form helpers and  more than this -->
<!-- url(url name as create ) -->
<div class="jumbotron">
    <h1>Edit article </h1>
    <form method="POST" action="">
        {% csrf_token %}

<!-- i  try this lines to render data to edit it but not work fine...By Mahmoud Shehata -->
        <!-- {{ArticleForm.cover_photo}} {{ArticleModel.cover_photo}}
        <br><br>
        {{ArticleForm.title}}   {{ArticleModel.title}}
        <br><br>
        {{ArticleForm.body}}{{ArticleModel.body}}   
        <br> -->
     <!-- lines end  -->
     <!-- but the bellow is working fine -->
     current is : {{ArticleModel.cover_photo}} <br>
        <input type="file" name="cover_photo" accept="image/*" id="id_cover_photo" value="{{ArticleModel.cover_photo}}">
        <br><br>
        <input type="text" name="title" maxlength="100" required="" id="id_title" value="{{ArticleModel.title}}">
        <br><br>
        <textarea name="body" cols="40" rows="10" maxlength="1000" required=""
            id="id_body">{{ArticleModel.body}}</textarea>
        <br><br>
        <button type="submit" class="btn-primary"> Update aritcle </button>
    </form>
</div>
{% endblock %}

Blog_project/Blog/templates/form.html
{% extends 'base.html' %}

{% block content %}
<!-- we can build form by own or we can user Django form  -->
<!-- that provides us with power of validation on input field and form helpers and  more than this -->
<!-- url(url name as create ) -->
<div class="jumbotron">
    <h1>Adding new article </h1>
    <form method="POST" action="{% url  'create' %}">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn-primary"> add aritcle </button>
    </form>
</div>
{% endblock %}

Blog_project/Blog/templates/index.html
{% extends 'nav.html' %}

{% block content %}

<!-- <ul> -->
{% for article in articles %}
<!-- <h1 style="color: green;">
        <li>{{article.title}}</li>
    </h1>  -->

<div class="container">
  <div class="jumbotron">

    <div class="card" style="width:700px">
      <img class="card-img-top" src="{{article.cover_photo.url}}" alt="Card image" style="width:100%">
      <div class="card-body">
        <!-- <h4 class="card-title">John Doe</h4> -->
        <h4 class="card-text">{{article.title}}</h4>
        <label for=""> created at :</label>
        <p class="card-text">{{article.posted_at | date:"d , m , y"}}</p>
        <label for=""> last updated at :</label>
        <p class="card-text">{{article.last_updated_at | date:"d , m , y"}}</p>
        <!-- <a href="#" class="btn btn-primary stretched-link">See Profile</a> -->
      </div>
    </div>
    <hr>
    <a href="{% url 'create'  %}" class="btn btn-success">Add Article</a>
    <a href="{% url 'delete' article.id %}" class="btn btn-danger">Delete Article</a>
    <a href="{% url 'update' article.id %}" class="btn btn-primary">Edit Article</a>



  </div>
</div>




{% endfor %}

{% endblock %}

Blog_project/Blog/templates/nav.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <title>Blogs</title>
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">BLogs</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
      aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home</a>
        </li>

        <li class="nav-item">
          <a class="nav-link disabled" href="#">Contact us</a>
        </li>
      </ul>
      <form class="form-inline mt-2 mt-md-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <!-- <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button> -->
        <a class="btn btn-outline-warning my-2 my-sm-0 mr-2" href="{% url 'users:login' %}">Log In</a>
        <a class="btn btn-outline-warning my-2 my-sm-0" href="{% url 'users:register' %}">Register</a>
      </form>
    </div>
  </nav>
  <br> <br> <br>
  {% block content %}

  {% endblock%}
</body>

</html>

Blog_project/users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}

<form action="{% url 'users:login' %}"></form>

{% endblock %}

Blog_project/users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}

<form action="{% url 'users:register' %}">
{{RegisterForm.as_p}}

</form>

{% endblock %}